import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

const ProductPage = () => {
  return <div>ProductPage</div>;
};

export default ProductPage;
